name: CI

on:
  push:
    branches-ignore:
      - "dependabot/*"
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Setup
      run: |
        git submodule update --init --recursive
        nuget restore src\engine.sln
    - name: MSBuild
      working-directory: src
      run: msbuild /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" engine.sln
    - name: Prepare artifacts
      id: windows-vars
      shell: cmd
      run: |
        set CONFIGURATION=${{ matrix.Configuration }}
        set PLATFORM=${{ matrix.Platform }}
        call xr_pack_build.cmd ARTIFACT_EDITION
        echo ::set-output name=Build_type::%ARTIFACT_EDITION%
    - name: Upload OpenXRay artifact
      uses: actions/upload-artifact@v2
      with:
        name: OpenXRay.${{ steps.windows-vars.outputs.Build_type }}.7z
        path: res\OpenXRay.${{ steps.windows-vars.outputs.Build_type }}.7z
    - name: Upload Utils
      uses: actions/upload-artifact@v2
      with:
        name: Utils.${{ steps.windows-vars.outputs.Build_type }}.7z
        path: res\Utils.${{ steps.windows-vars.outputs.Build_type }}.7z